### ISSUE TITLE
Active deals table refresh issue

### ISSUE THREAD

**Issue by johnwood2000** [coltoneshaw/3c-portfolio-manager#45]
**Describe the bug**
When in Active Deals and scrolled down in  deals, if auto-refresh is enabled, once it refreshes, it scrolls back higher or the top

**Screenshots**

**Desktop (please complete the following information):**

**Comment by coltoneshaw** [comment]
Thanks! I'm able to see this issue happening live but it seems to only happen on the first sync after the auto-sync is turned on. Are you seeing it on every sync, or just the first?

**Comment by johnwood2000** [comment]
I see the issue in every sync. I have sorted by "profit". It may be due to a change in the order of the deals, but it jumps every time it Syncs. I am using the Mac version. Hope this helps

**Comment by coltoneshaw** [comment]
Thanks! Are you on v0.4.1?

**Comment by johnwood2000** [comment]
Yes v0.4.1

**Comment by coltoneshaw** [comment]
Great! I think we have fixed it in the next large release coming out. I attached a video from the latest dev build of the project to show this issue resolved. If you don't see it fixed in the next release, go ahead and re-open this issue.

https://user-images.githubusercontent.com/46071821/134008957-3aac72d1-c95f-4125-a908-996686264944.mov
