### ISSUE TITLE
Active bot without active deals not used for risk calculation

### ISSUE THREAD

**Issue by MonkeyclawTim** [coltoneshaw/3c-portfolio-manager#46]
**Describe the bug**
I noticed today that when my QFL bots activated new deals, my risk increased although I have not changed any settings on my bots nor have I taken out any fiat. It appears that when a bot is active but it doesn't have any deals, the risk is not being taken into account. This gives a false sense of having a lower risk.

**To Reproduce**
Set up a QFL bot with a very high BO:SO, high MSTC and activate it (best to use a deep QFL amount so it doesn't actually start a trade!). Notice the risk doesn't change even if it would increase the risk by 50%.

**Comment by coltoneshaw** [comment]
Thanks, @MonkeyclawTim ! I know we talked via chat about it but in case anyone else is seeing this issue.

- Bot Planner = Risk of Active Bots **only**
- Stats - Risk of active deals **only**.

You will see differences if you have an active bot with an inactive deal. Or a ton of inactive bots with active deals. Working to get this data merged into a single risk metric. I've been hesitant since the metric was unreliable in the past, however, it looks like we have found a solution and i'm working on implementing that.

**Comment by coltoneshaw** [comment]
<img width="264" alt="Screen Shot 2021-09-22 at 9 42 13 PM" src="https://user-images.githubusercontent.com/46071821/134443341-fdf56ed6-2db3-41ed-91a2-b8d8cc1d782d.png">

@MonkeyclawTim - This will be fixed in v0.5.0. I've included the inactive metrics in the Stats page.

**Comment by MonkeyclawTim** [comment]
Woohoo!
